### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by russolsen** [Hal9000/livetext#1]
Note really an issue, just some thoughts. To wit:

I really like the idea - having a format that lets me have a mostly text, partially programmable document has been an idea that I've been poking at for a very long time. See, for example, https://github.com/russolsen/notroff and https://github.com/russolsen/md_inc.

Since I'm a happy user of asciidoc, the real value for me is in plug-ins and programmability and not in a new markup format. So I'm happy to see that one of the goals is to support various output formats. I suspect making a simple pass thru format would be easy, which would probably work with asciidoc.

The only other thing that strikes my eye -- and this could just be me -- is that I don't think the single token italics and bold solution is going to work for very long. I've just looked and the majority of my spans of italics are _several words long_.

Great stuff!

**Comment by Hal9000** [comment]
Shame on me for not having heard of asciidoc! I might never
have started this project. But I still like being able to extend in Ruby.

I also have multiword italics and such -- my notation with parentheses handles
most of that. I think I can live without spanning line breaks.
